# install python 3.7
language: python
python:
  - 3.7

branches:
  only:
    - master

# install poetry and dependencies
before_install:
  - pip install poetry
install:
  - poetry install

# install psql, create db and set db url
services:
  - postgresql
before_script:
  - psql -c 'create database test;' -U postgres
env:
  - DB_URL=postgresql://postgres@localhost/test

# run pre-commit hooks
script:
  - poetry run pre-commit run -a
