[tool.poetry]
name = "repka"
version = "0.1.0"
description = "Python repository pattern implementation"
authors = ["potykion <potykion@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
pydantic = "^0.29.0"
sqlalchemy = "^1.3"
aiopg = "^0.16.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
